var annotated =
[
    [ "Lobby", "db/dd7/class_lobby.html", "db/dd7/class_lobby" ],
    [ "PN_OP", "d6/d0b/struct_p_n___o_p.html", "d6/d0b/struct_p_n___o_p" ],
    [ "PNArg", "d0/d61/struct_p_n_arg.html", "d0/d61/struct_p_n_arg" ],
    [ "PNAsm", "dc/dbd/struct_p_n_asm.html", "dc/dbd/struct_p_n_asm" ],
    [ "PNBHeader", "de/d35/struct_p_n_b_header.html", "de/d35/struct_p_n_b_header" ],
    [ "PNBoolean", "dc/d77/class_p_n_boolean.html", "dc/d77/class_p_n_boolean" ],
    [ "PNBytes", "d5/da9/struct_p_n_bytes.html", "d5/da9/struct_p_n_bytes" ],
    [ "PNClosure", "d3/de9/struct_p_n_closure.html", "d3/de9/struct_p_n_closure" ],
    [ "PNCont", "d7/da4/struct_p_n_cont.html", "d7/da4/struct_p_n_cont" ],
    [ "PNData", "d1/de5/struct_p_n_data.html", "d1/de5/struct_p_n_data" ],
    [ "PNDecimal", "d3/d12/struct_p_n_decimal.html", "d3/d12/struct_p_n_decimal" ],
    [ "PNError", "d1/dc2/struct_p_n_error.html", "d1/dc2/struct_p_n_error" ],
    [ "PNFile", "d5/d55/struct_p_n_file.html", "d5/d55/struct_p_n_file" ],
    [ "PNFwd", "d4/d78/struct_p_n_fwd.html", "d4/d78/struct_p_n_fwd" ],
    [ "PNJumps", "d3/d7b/struct_p_n_jumps.html", "d3/d7b/struct_p_n_jumps" ],
    [ "PNLick", "df/dad/struct_p_n_lick.html", "df/dad/struct_p_n_lick" ],
    [ "PNLoop", "d1/d49/struct_p_n_loop.html", "d1/d49/struct_p_n_loop" ],
    [ "PNMemory", "de/db4/struct_p_n_memory.html", "de/db4/struct_p_n_memory" ],
    [ "PNNumber", "d9/d08/class_p_n_number.html", "d9/d08/class_p_n_number" ],
    [ "PNObject", "da/dbb/struct_p_n_object.html", "da/dbb/struct_p_n_object" ],
    [ "PNProto", "d6/d4e/struct_p_n_proto.html", "d6/d4e/struct_p_n_proto" ],
    [ "PNSource", "dc/dc6/struct_p_n_source.html", "dc/dc6/struct_p_n_source" ],
    [ "PNString", "d5/deb/struct_p_n_string.html", "d5/deb/struct_p_n_string" ],
    [ "PNTable", "d3/d73/struct_p_n_table.html", "d3/d73/struct_p_n_table" ],
    [ "PNTarget", "d6/d06/struct_p_n_target.html", "d6/d06/struct_p_n_target" ],
    [ "PNTuple", "df/d30/struct_p_n_tuple.html", "df/d30/struct_p_n_tuple" ],
    [ "PNVtable", "d7/de2/struct_p_n_vtable.html", "d7/de2/struct_p_n_vtable" ],
    [ "PNWeakRef", "d2/d49/struct_p_n_weak_ref.html", "d2/d49/struct_p_n_weak_ref" ],
    [ "Potion_State", "d2/dcd/struct_potion___state.html", "d2/dcd/struct_potion___state" ]
];